spring:
  application:
    name: sboot-banking-directory-api
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:h2:mem:branchesdirectory
#    url: jdbc:h2:file:./branchesdirectory
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  h2:
    console:
      path: /h2-console
      enabled: true

  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10min=600000 | 2min=120000 | 3min=180000

  redis:
    host: localhost
    port: 6379
    timeout: 3000  # timeout in milliseconds

  security:
    user:
      name: admin
      password: admin

cache-ttl:
  branches-distances-cache-ttl-in-min: 2

app:
  users:
    - username: admin
      password: admin
      role: ADMIN
    - username: user
      password: user
      role: USER